Practico 02
leonsch1997/frro-soporte-2019-03 pull request #2
Opened 2019-04-03 20:13 UTC by alesoftware

Practico 02

2019-04-03 20:26 UTC, Franr requested changes

2019-04-03 20:26 UTC, Franr commented on practico_02/ejercicio_04.py
> +        edad_actual=int(input("ingrese edad actual: "))
La edad actual se saca de la superclase Persona, de la cual no heredaron, faltó eso

2019-04-03 20:36 UTC, leonsch1997 commented on practico_02/ejercicio_04.py
> +        edad_actual=int(input("ingrese edad actual: "))
claro, lo tenemos que cambiar profe o ya esta aprobado?

2019-04-03 20:59 UTC, Franr commented on practico_02/ejercicio_04.py
> +        edad_actual=int(input("ingrese edad actual: "))
Hay que cambiarlo

2019-04-06 15:32 UTC, leonsch1997 commented on practico_02/ejercicio_04.py
> +        edad_actual=int(input("ingrese edad actual: "))
corregido Fran!! tengo que volver a hacer el pull request o se actualiza solo?

2019-04-06 15:49 UTC, Franr approved these changes

2019-04-06 15:49 UTC, merged